// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string      `json:"token"`
	Menus interface{} `json:"menus"`
}

type ManagerAddReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	RoleId   int64  `json:"role_id"`
	Status   int    `json:"status"`
}

type ManagerDeleteReq struct {
	Id int64 `json:"id"`
}

type ManagerListReq struct {
	Username string `json:"username"`
	RoleName string `json:"role_name"`
	PaginateReq
}

type ManagerListResp struct {
	Total int         `json:"total"`
	Data  interface{} `json:"data"`
}

type ManagerUpdateReq struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	RoleId   int64  `json:"role_id"`
	Status   int    `json:"status,range=[1:2]"`
}

type NilMessage struct {
}

type PaginateReq struct {
	Page int `json:"page"`
	Size int `json:"size"`
}

type RoleAddReq struct {
	Name       string `json:"name"`
	Permission string `json:"permission"`
	Status     int    `json:"status"`
}

type RoleDeleteReq struct {
	Id int64 `json:"id"`
}

type RoleListReq struct {
	Name string `json:"name"`
	PaginateReq
}

type RoleListResp struct {
	Total int         `json:"total"`
	Data  interface{} `json:"data"`
}

type RoleUpdateReq struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Permission string `json:"permission"`
	Status     int    `json:"status"`
}
