// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type ManagerAddReq struct {
}

type ManagerAddResp struct {
}

type ManagerListReq struct {
}

type ManagerListResp struct {
}

type ManagerLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type ManagerLoginResp struct {
	Token string   `json:"token"`
	Menus []string `json:"menus"`
}

type ManagerRoleAddReq struct {
}

type ManagerRoleAddResp struct {
}

type ManagerRoleListReq struct {
}

type ManagerRoleListResp struct {
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}
