// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string   `json:"token"`
	Menus []string `json:"menus"`
}

type ManagerAddReq struct {
}

type ManagerAddResp struct {
}

type ManagerDeleteReq struct {
}

type ManagerDeleteResp struct {
}

type ManagerListReq struct {
}

type ManagerListResp struct {
}

type ManagerUpdateReq struct {
}

type ManagerUpdateResp struct {
}

type RoleAddReq struct {
}

type RoleAddResp struct {
}

type RoleDeleteReq struct {
}

type RoleDeleteResp struct {
}

type RoleListReq struct {
}

type RoleListResp struct {
}

type RoleUpdateReq struct {
}

type RoleUpdateResp struct {
}
