// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	auth "next.com/next/backend/internal/handler/auth"
	systemmanagers "next.com/next/backend/internal/handler/system/managers"
	systemroles "next.com/next/backend/internal/handler/system/roles"
	"next.com/next/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/manager/add",
					Handler: systemmanagers.ManagerAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/manager/delete",
					Handler: systemmanagers.ManagerDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/manager/list",
					Handler: systemmanagers.ManagerListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/manager/update",
					Handler: systemmanagers.ManagerUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/role/add",
					Handler: systemroles.RoleAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/delete",
					Handler: systemroles.RoleDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/list",
					Handler: systemroles.RoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/update",
					Handler: systemroles.RoleUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
