// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	system "next.com/next/backend/internal/handler/system"
	"next.com/next/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: ManagerLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: system.BackendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mangerList",
				Handler: system.ManagerListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mangerRoleList",
				Handler: system.ManagerRoleListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
