// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	auth "next.com/next/backend/internal/handler/auth"
	systemmanagers "next.com/next/backend/internal/handler/system/managers"
	systemroles "next.com/next/backend/internal/handler/system/roles"
	"next.com/next/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/Manager/add",
				Handler: systemmanagers.ManagerAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/Manager/delete",
				Handler: systemmanagers.ManagerDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/Manager/update",
				Handler: systemmanagers.ManagerUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/manager/list",
				Handler: systemmanagers.ManagersHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/role/add",
				Handler: systemroles.RoleAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/delete",
				Handler: systemroles.RoleDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/list",
				Handler: systemroles.ManagersRoleListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/update",
				Handler: systemroles.RoleUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
